
services:
  mongo:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./gestion-smartphone-backend
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - ./gestion-smartphone-backend/.env
    depends_on:
      - mongo

  frontend:
    build: ./gestion-smartphone-frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mongo-data:
