services:
  mongo:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./gestion-smartphone-backend
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - ./gestion-smartphone-backend/.env
    depends_on:
      - mongo

  frontend:
    build: ./gestion-smartphone-frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend

  # 🗄️ Base de données pour SonarQube
  postgres:
    image: postgres:15
    container_name: sonarqube-db
    restart: always
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    volumes:
      - postgres-data:/var/lib/postgresql/data

  # 🧠 SonarQube Server
  sonarqube:
    image: sonarqube:community
    container_name: sonarqube
    restart: always
    ports:
      - "9000:9000"   # Interface Web SonarQube
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://postgres:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    depends_on:
      - postgres
    volumes:
      - sonarqube-data:/opt/sonarqube/data
      - sonarqube-logs:/opt/sonarqube/logs
      - sonarqube-extensions:/opt/sonarqube/extensions

volumes:
  mongo-data:
  postgres-data:
  sonarqube-data:
  sonarqube-logs:
  sonarqube-extensions:
