services:
  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./gestion-smartphone-backend
    container_name: backend
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - ./gestion-smartphone-backend/.env
    depends_on:
      - mongo

  frontend:
    build: ./gestion-smartphone-frontend
    container_name: frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend

  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    image: jenkins-docker
    container_name: jenkins
    restart: always
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  mongo-data:
  jenkins_home:

