services:
  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./gestion-smartphone-backend
    container_name: backend
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - ./gestion-smartphone-backend/.env
    depends_on:
      - mongo

  frontend:
    build: ./gestion-smartphone-frontend
    container_name: frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: always
    user: root
    ports:
      - "8080:8080"   # Accès interface Jenkins
      - "50000:50000" # Pour les agents (optionnel)
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock  # permet à Jenkins de contrôler Docker
      - /usr/bin/docker:/usr/bin/docker            # accès à la commande docker

volumes:
  mongo-data:
  jenkins_home:
