FROM jenkins/jenkins:lts

USER root

# Installer Docker CLI et docker-compose
RUN apt-get update && \
    apt-get install -y curl gnupg lsb-release && \
    curl -fsSL https://get.docker.com | sh && \
    apt-get install -y docker-compose-plugin

# Remettre l’utilisateur Jenkins
USER jenkins
